/**
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated by: tests/scripts/generate-helpers.ts
 * Source: gcp_tool.html
 * Generated: 2025-10-28T00:14:00.262Z
 *
 * This file contains type-safe selectors for all interactive elements
 * in the GCP setup wizard. Use these in your Playwright tests instead of
 * hard-coding selectors.
 *
 * Example usage:
 *   import { selectors } from "./helpers/gcp-selectors";
 *   await page.click(selectors.saveProjectBtn);
 */

export const selectors = {
  // ==================== BUTTONS ====================
  /** 📋 View All GCP Projects */
  viewProjectsBtn: '[data-testid="view-projects-btn"]',
  /** 🔄 Reset Setup */
  resetSetupBtn: '[data-testid="reset-setup-btn"]',
  /** 🗑️ Open GCP Console to Delete */
  deleteProjectBtn: '[data-testid="delete-project-btn"]',
  /** Save & Continue */
  saveProjectBtn: '[data-testid="save-project-btn"]',
  /** 📋 Copy */
  copyProjectIdBtn: '[data-testid="copy-project-id-btn"]',
  /** Mark as Done */
  markProjectDoneBtn: '[data-testid="mark-project-done-btn"]',
  /** Mark as Done */
  markApiDoneBtn: '[data-testid="mark-api-done-btn"]',
  /** Mark as Done */
  markConsentDoneBtn: '[data-testid="mark-consent-done-btn"]',
  /** Save Credentials */
  saveCredentialsBtn: '[data-testid="save-credentials-btn"]',

  // ==================== LINKS (styled as buttons) ====================
  /** Open GCP Console → */
  createProjectBtn: '[data-testid="create-project-btn"]',
  /** Enable Calendar API → */
  enableCalendarApiBtn: '[data-testid="enable-calendar-api-btn"]',
  /** Enable OAuth2 API → */
  enableOauth2ApiBtn: '[data-testid="enable-oauth2-api-btn"]',
  /** Open OAuth Consent → */
  configureConsentBtn: '[data-testid="configure-consent-btn"]',
  /** Create OAuth Client → */
  createOauthCredsBtn: '[data-testid="create-oauth-creds-btn"]',

  // ==================== INPUTS ====================
  /** wellknown-cal-dev */
  projectIdInput: '[data-testid="project-id-input"]',
  /** Same as Project ID */
  projectNameInput: '[data-testid="project-name-input"]',
  /** your-id.apps.googleusercontent.com */
  clientIdInput: '[data-testid="client-id-input"]',
  /** your-secret */
  clientSecretInput: '[data-testid="client-secret-input"]',

  // ==================== STATUS BADGES ====================
  step1Status: '[data-testid="step1-status"]',
  step2Status: '[data-testid="step2-status"]',
  step3Status: '[data-testid="step3-status"]',
  step4Status: '[data-testid="step4-status"]',
  step5Status: '[data-testid="step5-status"]',

  // ==================== MESSAGES ====================
  projectIdError: '[data-testid="project-id-error"]',
  successMessage: '[data-testid="success-message"]',
} as const;

/**
 * Type-safe selector keys
 */
export type SelectorKey = keyof typeof selectors;

/**
 * Helper function to get a selector by key
 */
export function getSelector(key: SelectorKey): string {
  return selectors[key];
}