package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println("=== wellknown Basic Examples ===\n")

	// Google Calendar Example
	fmt.Println("1. Google Calendar Event:")
	googleCalendarURL := "googlecalendar://render?action=CREATE&text=Team%20Meeting&dates=20251026T140000Z/20251026T150000Z&details=Discuss%20Q4%20roadmap&location=Conference%20Room%20A"
	fmt.Printf("   URL: %s\n\n", googleCalendarURL)

	// Apple Calendar Example
	fmt.Println("2. Apple Calendar Event:")
	timestamp := time.Now().Unix()
	appleCalendarURL := fmt.Sprintf("calshow:%d", timestamp)
	fmt.Printf("   URL: %s\n\n", appleCalendarURL)

	// Google Maps Example
	fmt.Println("3. Google Maps Navigation:")
	googleMapsURL := "comgooglemaps://?q=Space+Needle,Seattle+WA&center=47.6205,-122.3493&zoom=14"
	fmt.Printf("   URL: %s\n\n", googleMapsURL)

	// Apple Maps Example
	fmt.Println("4. Apple Maps Navigation:")
	appleMapsURL := "maps://?q=Space+Needle,Seattle+WA&sll=47.6205,-122.3493&z=14"
	fmt.Printf("   URL: %s\n\n", appleMapsURL)

	// Google Drive Example
	fmt.Println("5. Google Drive File:")
	googleDriveURL := "googledrive://1a2b3c4d5e6f7g8h9i0j"
	fmt.Printf("   URL: %s\n\n", googleDriveURL)

	// Apple Files Example
	fmt.Println("6. Apple Files/iCloud:")
	appleFilesURL := "shareddocuments://Documents/MyFolder/document.pdf"
	fmt.Printf("   URL: %s\n\n", appleFilesURL)

	// Email Example (Universal)
	fmt.Println("7. Email (Universal):")
	emailURL := "mailto:example@example.com?subject=Hello&body=This%20is%20a%20test"
	fmt.Printf("   URL: %s\n\n", emailURL)

	fmt.Println("=== End of Examples ===")
	fmt.Println("\nNote: These are example deep link URLs.")
	fmt.Println("In a real application, these would be generated by the wellknown library.")
}
