#!/usr/bin/env bun
/**
 * Test Helper Generator - Auto-generates type-safe test selectors from HTML
 *
 * Purpose: Read HTML analysis and generate TypeScript helper file with ALL selectors
 *
 * Benefits:
 * - 100% type-safe (TypeScript autocomplete for all selectors)
 * - Self-documenting (comments explain what each selector is for)
 * - Auto-updated (regenerate whenever HTML changes)
 * - DRY (single source of truth for test selectors)
 */

import * as fs from 'fs';
import * as path from 'path';

interface InteractiveElement {
  type: 'button' | 'input' | 'link' | 'status' | 'message';
  testId: string | null;
  id: string | null;
  text: string | null;
  selector: string;
}

interface AnalysisResult {
  file: string;
  totalElements: number;
  withTestId: number;
  withoutTestId: number;
  elements: InteractiveElement[];
}

/**
 * Convert data-testid to camelCase variable name
 * Example: "save-project-btn" → "saveProjectBtn"
 */
function toCamelCase(testId: string): string {
  return testId.replace(/-([a-z])/g, (_, letter) => letter.toUpperCase());
}

/**
 * Generate TypeScript helper file
 */
function generateHelpers(analysis: AnalysisResult): string {
  // Only process elements that have data-testid
  const elementsWithTestId = analysis.elements.filter(e => e.testId !== null && e.testId !== undefined);

  // Group by type for better organization
  const byType = {
    button: elementsWithTestId.filter(e => e.type === 'button'),
    link: elementsWithTestId.filter(e => e.type === 'link'),
    input: elementsWithTestId.filter(e => e.type === 'input'),
    status: elementsWithTestId.filter(e => e.type === 'status'),
    message: elementsWithTestId.filter(e => e.type === 'message'),
  };

  const lines: string[] = [];

  // Header
  lines.push('/**');
  lines.push(' * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY');
  lines.push(' * Generated by: tests/scripts/generate-helpers.ts');
  lines.push(` * Source: ${analysis.file}`);
  lines.push(` * Generated: ${new Date().toISOString()}`);
  lines.push(' *');
  lines.push(' * This file contains type-safe selectors for all interactive elements');
  lines.push(' * in the GCP setup wizard. Use these in your Playwright tests instead of');
  lines.push(' * hard-coding selectors.');
  lines.push(' *');
  lines.push(' * Example usage:');
  lines.push(' *   import { selectors } from "./helpers/gcp-selectors";');
  lines.push(' *   await page.click(selectors.saveProjectBtn);');
  lines.push(' */');
  lines.push('');

  // Selectors object
  lines.push('export const selectors = {');
  lines.push('  // ==================== BUTTONS ====================');

  byType.button.forEach(el => {
    const varName = toCamelCase(el.testId!);
    const comment = el.text ? `  /** ${el.text} */` : '';
    if (comment) lines.push(comment);
    lines.push(`  ${varName}: '[data-testid="${el.testId}"]',`);
  });

  lines.push('');
  lines.push('  // ==================== LINKS (styled as buttons) ====================');

  byType.link.forEach(el => {
    const varName = toCamelCase(el.testId!);
    const comment = el.text ? `  /** ${el.text} */` : '';
    if (comment) lines.push(comment);
    lines.push(`  ${varName}: '[data-testid="${el.testId}"]',`);
  });

  lines.push('');
  lines.push('  // ==================== INPUTS ====================');

  byType.input.forEach(el => {
    const varName = toCamelCase(el.testId!);
    const comment = el.text ? `  /** ${el.text} */` : '';
    if (comment) lines.push(comment);
    lines.push(`  ${varName}: '[data-testid="${el.testId}"]',`);
  });

  lines.push('');
  lines.push('  // ==================== STATUS BADGES ====================');

  byType.status.forEach(el => {
    const varName = toCamelCase(el.testId!);
    lines.push(`  ${varName}: '[data-testid="${el.testId}"]',`);
  });

  lines.push('');
  lines.push('  // ==================== MESSAGES ====================');

  byType.message.forEach(el => {
    const varName = toCamelCase(el.testId!);
    lines.push(`  ${varName}: '[data-testid="${el.testId}"]',`);
  });

  lines.push('} as const;');
  lines.push('');

  // Type exports for better IDE support
  lines.push('/**');
  lines.push(' * Type-safe selector keys');
  lines.push(' */');
  lines.push('export type SelectorKey = keyof typeof selectors;');
  lines.push('');

  lines.push('/**');
  lines.push(' * Helper function to get a selector by key');
  lines.push(' */');
  lines.push('export function getSelector(key: SelectorKey): string {');
  lines.push('  return selectors[key];');
  lines.push('}');

  return lines.join('\n');
}

/**
 * Main execution
 */
function main() {
  const analysisPath = path.join(__dirname, '../.cache/html-analysis.json');
  const outputPath = path.join(__dirname, '../helpers/gcp-selectors.ts');

  // Read analysis
  if (!fs.existsSync(analysisPath)) {
    console.error(`❌ Analysis file not found: ${analysisPath}`);
    console.error('   Run: bun scripts/analyze-html.ts first\n');
    process.exit(1);
  }

  const analysis: AnalysisResult = JSON.parse(fs.readFileSync(analysisPath, 'utf-8'));

  console.log('🔧 Generating test helpers...\n');

  // Generate helpers
  const content = generateHelpers(analysis);

  // Write to file
  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content);

  console.log(`✅ Generated: ${outputPath}`);
  console.log(`📊 Total selectors: ${analysis.withTestId}`);
  console.log(`🎯 Type-safe, auto-complete enabled!\n`);

  // Show example usage
  console.log('Example usage in your tests:');
  console.log('');
  console.log('  import { selectors } from "./helpers/gcp-selectors";');
  console.log('');
  console.log('  await page.click(selectors.saveProjectBtn);');
  console.log('  await page.fill(selectors.projectIdInput, "my-project");');
  console.log('  await expect(page.locator(selectors.step1Status)).toContainText("Done");');
  console.log('');
}

main();
